name: rsync
version: dev
slug: rsync
description: Sync folders to a remote machine via ssh and rsync.
url: https://github.com/Poeschl-HomeAssistant-Addons/rsync
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
homeassistant: 0.115.0
boot: manual
init: false
image: ghcr.io/poeschl-homeassistant-addons/rsync-{arch}
ports: {}
ports_description: {}
map:
  - share:rw
  - config:rw
  - backup:rw
  - addons:rw
  - ssl:rw
  - media:rw
schema:
  private_key_file: match(^/ssl/.+)
  username: str
  folders:
    - local: str
      remote: str
      options: str?
      direction: str?  # 'push' (local to remote) ou 'pull' (remote to local)
  remote_host: str
  remote_port: port?
options:
  private_key_file: /ssl/rsync/id_rsa
  username: user
  folders:
    - local: /config
      remote: /home/user
      direction: push  # default, push local to remote
  remote_host: ""
